# Generated by Django 3.2.23 on 2024-01-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
